name: DEV Test, Lint & Format

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Check Backend
        working-directory: ./backend
        env:
          BACKEND_ENV_FILE: ${{ secrets.BACKEND_ENV }}
        run: |
          echo $BACKEND_ENV_FILE | base64 --decode > .env
          npm install
          npm run lint
          npm run format:check
          npm test
      - name: Check Frontend
        working-directory: ./frontend
        env:
          FRONTEND_ENV_FILE: ${{ secrets.FRONTEND_ENV }}
        run: |
          echo $FRONTEND_ENV_FILE | base64 --decode > .env
          npm install
          npm run lint
          npm run format:check
